/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceItem, Stylist, ReviewItem } from './types';

export const SERVICES: Record<'ca' | 'es', ServiceItem[]> = {
  ca: [
    {
      id: 'hair-1',
      name: 'Tallat de Cabell Unisex & Estilisme',
      category: 'perruqueria',
      duration: 45,
      price: 22,
      description: 'Asessorament de visatgisme personalitzat, rentat analgèsic amb massatge capil·lar, tallat a tisora o navalla i definició final.',
      isPopular: true,
    },
    {
      id: 'hair-2',
      name: 'Coloració Orgànica Premium & Brillantor',
      category: 'perruqueria',
      duration: 90,
      price: 36,
      description: 'Tractament de color professional amb tints lliures d\'amoníac i enriquits amb olis naturals. Protegeix i nodreix la fibra capil·lar.',
    },
    {
      id: 'hair-3',
      name: 'Tècnica Balayage de Sedició Artesana',
      category: 'perruqueria',
      duration: 150,
      price: 75,
      description: 'Metxes degradades pintades a mà alçada per a un contrast natural, lluminós i tridimensional. Inclou tractament matitzador de brillantor.',
      isPopular: true,
    },
    {
      id: 'hair-4',
      name: 'Tractament Reconstructor d\'Àcid Hialurònic & Queratina',
      category: 'perruqueria',
      duration: 75,
      price: 55,
      description: 'Cura intensiva anti-frizz que reestructura profundament els cabells deshidratats o danyats tipus mirall, aportant cos i brillantor de seda.',
    },
    {
      id: 'hair-5',
      name: 'Pentinat Editorial, Brushing & Recollits d\'Esdeveniment',
      category: 'perruqueria',
      duration: 60,
      price: 28,
      description: 'Pentinar artístic o recollit especial per a bodes, batejos, comunions i festes locals, adaptat al teu estil exclusiu o vestit.',
    },
    {
      id: 'beauty-1',
      name: 'Manicura Completa Wellness amb Esmaltat Semiperminent',
      category: 'estetica',
      duration: 50,
      price: 24,
      description: 'Retallat i limat de ungles, cura de cutícules, exfoliació amb sals marines, massatge hidratant de mans i esmaltat professional de llarga durada.',
      isPopular: true,
    },
    {
      id: 'beauty-2',
      name: 'Pedicura Spa Rehidratant profunda',
      category: 'estetica',
      duration: 60,
      price: 32,
      description: 'Bany relaxant amb herbes de muntanya, eliminació de dureses profunda, exfoliació aromàtica, massatge circulatori i esmaltat.',
    },
    {
      id: 'beauty-3',
      name: 'Ritual Facial d\'Hidratació Botànica Avançada',
      category: 'estetica',
      duration: 75,
      price: 48,
      description: 'Neteja facial profunda amb vapor actiu, peeling enzimàtic, extirpació d\'impureses, sèrum concentrat enriquït i massatge facial llevant.',
      isPopular: true,
    },
    {
      id: 'beauty-4',
      name: 'Disseny de Celles & Depilació de Precisió',
      category: 'estetica',
      duration: 30,
      price: 14,
      description: 'Disseny personalitzat de la mirada prenent mides geomètriques del rostre, depilació delicada amb fil o cera tèbia de camomila.',
    },
  ],
  es: [
    {
      id: 'hair-1',
      name: 'Corte de Cabello Unisex & Estilismo',
      category: 'perruqueria',
      duration: 45,
      price: 22,
      description: 'Asesoramiento de visajismo personalizado, lavado analgésico con masaje capilar, corte a tijera o navaja y definición final.',
      isPopular: true,
    },
    {
      id: 'hair-2',
      name: 'Coloración Orgánica Premium & Brillo',
      category: 'perruqueria',
      duration: 90,
      price: 36,
      description: 'Tratamiento de color profesional con tintes libres de amoníaco y enriquecidos con aceites naturales. Protege y nutre la fibra capilar.',
    },
    {
      id: 'hair-3',
      name: 'Técnica Balayage de Creación Artesanal',
      category: 'perruqueria',
      duration: 150,
      price: 75,
      description: 'Mechas degradadas pintadas a mano alzada para un contraste natural, luminoso y tridimensional. Incluye tratamiento matizador de brillo.',
      isPopular: true,
    },
    {
      id: 'hair-4',
      name: 'Tratamiento Reconstructor de Ácido Hialurónico & Queratina',
      category: 'perruqueria',
      duration: 75,
      price: 55,
      description: 'Cuidado intensivo anti-frizz que reestructura profundamente los cabellos deshidratados o dañados, aportando cuerpo y brillo sedoso.',
    },
    {
      id: 'hair-5',
      name: 'Peinado Editorial, Brushing & Recogidos de Evento',
      category: 'perruqueria',
      duration: 60,
      price: 28,
      description: 'Peinado artístico o recogido especial para bodas, bautizos, comuniones y fiestas locales, adaptado a tu estilo exclusivo.',
    },
    {
      id: 'beauty-1',
      name: 'Manicura Completa Wellness con Esmaltado Semipermanente',
      category: 'estetica',
      duration: 50,
      price: 24,
      description: 'Recortado y limado de uñas, cuidado de cutículas, exfoliación con sales marinas, masaje hidratante de manos y esmaltado profesional de larga duración.',
      isPopular: true,
    },
    {
      id: 'beauty-2',
      name: 'Pedicura Spa Rehidratante profunda',
      category: 'estetica',
      duration: 60,
      price: 32,
      description: 'Baño relajante con hierbas silvestres, eliminación de durezas profunda, exfoliación aromática, masaje circulatorio y esmaltado.',
    },
    {
      id: 'beauty-3',
      name: 'Ritual Facial de Hidratación Botánica Avanzada',
      category: 'estetica',
      duration: 75,
      price: 48,
      description: 'Limpieza facial profunda con vapor activo, peeling enzimático, extracción de impurezas, suero concentrado y masaje levantamiento facial.',
      isPopular: true,
    },
    {
      id: 'beauty-4',
      name: 'Diseño de Cejas & Depilación de Precisión',
      category: 'estetica',
      duration: 30,
      price: 14,
      description: 'Diseño personalizado de la mirada considerando medidas geométricas de tu rostro y depilación con hilo o cera tibia de manzanilla.',
    },
  ],
};

export const STYLISTS: Record<'ca' | 'es', Stylist[]> = {
  ca: [
    {
      id: 'stylist-1',
      name: 'Elisenda Tubau',
      role: 'Directora & Estilista Principal',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
      bio: 'Amb més de 15 anys d\'experiència en l\'alta perruqueria i l\'estètica. Creador de somriures i looks exclusius a l\'Espluga de Francolí, apassionada de la salut capil·lar orgànica i els degradats balayage.',
    },
    {
      id: 'stylist-2',
      name: 'Marta Soler',
      role: 'Especialista en Estètica & Benestar',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400',
      bio: 'Especialitzada en teràpies d\'hidratació facial, bellesa d\'ungles i perfilat de celles geomètric. Treballa per fer florir la teva brillantor interior lliurant pau integral.',
    },
  ],
  es: [
    {
      id: 'stylist-1',
      name: 'Elisenda Tubau',
      role: 'Directora & Estilista Principal',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
      bio: 'Con más de 15 años de experiencia en alta peluquería y estética. Creadora de sonrisas y looks exclusivos en L\'Espluga de Francolí, apasionada de la salud capilar orgánica y los degradados balayage.',
    },
    {
      id: 'stylist-2',
      name: 'Marta Soler',
      role: 'Especialista en Estética & Bienestar',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400',
      bio: 'Especializada en terapias de hidratación facial, belleza de manos y pies y perfilado geométrico facial. Trabaja para hacer aflorar tu esplendor natural entregando paz integral.',
    },
  ],
};

export const REVIEWS: ReviewItem[] = [
  {
    id: 'rev-1',
    author: 'Anna Farré (L\'Espluga de Francolí)',
    date: '2026-05-18',
    rating: 5,
    comment: 'L\'atenció d\'Elisenda és increïble. Em va fer unes metxes balayage que han superat completament les meves expectatives. Tothom em demana on me les he fet! Els tractaments capil·lars orgànics deixen un olor i textura espectaculars.',
  },
  {
    id: 'rev-2',
    author: 'Joan Rendé',
    date: '2026-05-28',
    rating: 5,
    comment: 'Un autèntic servei professional de confiança. El tallat és impecable i el massatge capil·lar durant el rentat és d\'un altre nivell, súper relaxant després de la feina.',
  },
  {
    id: 'rev-3',
    author: 'Laura Palau (Montblanc)',
    date: '2026-06-02',
    rating: 5,
    comment: 'Sempre vinc des de Montblanc només per fer-me la manicura spa i la cura facial amb la Marta. Té una delicadesa i cura extraordinari, el lloc transmet molta pau i professionalitat de saló executiu.',
  },
];

export const GALLERY_IMGS = [
  {
    id: 'gal-1',
    title: 'Balayage Mel i Arena Col·lecció Estiu',
    tech: 'Balayage amb matís orgànic',
    url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'gal-2',
    title: 'Recollit de Núvia Bohemi',
    tech: 'Crespat i textures romàntiques',
    url: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'gal-3',
    title: 'Bob Francès de Precisió',
    tech: 'Tallat geometritzat amb navalla',
    url: 'https://images.unsplash.com/photo-1605497746445-97d1b0a9eead?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'gal-4',
    title: 'Metxes Babylights Roges i Cobres',
    tech: 'Il·luminació de base fosca',
    url: 'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'gal-5',
    title: 'Manicura Semiperminent Detall Or',
    tech: 'Cura premium i nail art subtil',
    url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'gal-6',
    title: 'Tractament de Queratina i Brillantor Espejo',
    tech: 'Cauterització tèrmica de queratina',
    url: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=600',
  },
];

export const TRANSLATIONS = {
  ca: {
    metaTitle: 'Perruqueria Elisenda',
    metaSub: 'Estilisme, Cabell & Tractaments Estètics de Saló',
    navHome: 'Inici',
    navServices: 'Serveis',
    navGallery: 'Saber-ne més / Galeria',
    navBooking: 'Cita Online',
    navAbout: 'Història & Revisions',
    navContact: 'Contacte i Horari',
    heroTag: 'Elegància, benestar i tractament de confiança',
    heroTitle: 'Revela la teva bellesa natural amb criteri professional',
    heroSub: 'Saló executiu pro especialista en estilisme capil·lar orgànic, balayage, pentinats d\'esdeveniments i cures estètiques de pell d\'alt nivell a l\'Espluga de Francolí.',
    heroCTA1: 'Demanar Cita Online',
    heroCTA2: 'Veure els Serveis',
    servicesTitle: 'Serveis Distingits',
    servicesSub: 'Fes un cop d\'ull a la nostra carta professional. Cada ritual està adaptat amb cura a les teves característiques físiques i personals.',
    catHair: 'Perruqueria i Salut Capil·lar',
    catBeauty: 'Estètica, Mans i Facial',
    mins: 'min',
    bookNow: 'Reservar',
    popularBadge: 'Més Sol·licitat',
    galleryTitle: 'Art en moviment',
    gallerySub: 'Instantànies reals del nostre treball, acabats de color, manicures, recollits d\'esdeveniments i línies de tallat professional.',
    bookingTitle: 'El teu moment de benestar',
    bookingSub: 'Inicia el procés segur. Tria el servei, l\'estilista de confiança i la franja horària per rebre un servei exquisit i sense esperes.',
    selectService: 'Selecciona un Servei',
    selectStylist: 'Escull l\'Estilista',
    anyStylist: 'Qualsevol professional (Escollir Marta o Elisenda)',
    selectDateTime: 'Dia i Hora perfectes',
    personalData: 'Dades de Contacte',
    placeholderName: 'El teu nom i cognom',
    placeholderPhone: 'Telèfon (exemple: 600 000 000)',
    placeholderNotes: 'Té algun comentari? (Al·lèrgia, cabell llarg o curt...)',
    buttonConfirmBooking: 'Confirmar Reserva i Rebre Rebut',
    anyStylistLabel: 'Indiferent',
    bookingSuccess: 'La teva cita s\'ha registrat amb èxit!',
    bookingSuccessSub: 'Ens veiem molt aviat! A sota tens el teu rebut que pots ensenyar directament des del mòbil. Hem desat també l\'historial en la memòria local.',
    receiptTitle: 'Resum del Rebut',
    receiptCode: 'Codi de Seguretat',
    receiptStylist: 'Personal tècnic',
    receiptDateTime: 'Data i hora',
    receiptPrice: 'Total estumat a pagar',
    bookingHistoryTitle: 'Les teves darreres reserves',
    aboutTitle: 'Més de 15 anys d\'artesania del cabell',
    aboutSub: 'El saló d\'alta costura capil·lar l\'Espluga de Francolí',
    aboutText1: 'Fundat per Elisenda Tubau, Perruqueria Elisenda va néixer sota la voluntat de portar l\'equilibri estètic de la gran ciutat a la nostra comarca de la Conca de Barberà. Creiem que cuidar el cabell és tenir cura de la salut d\'un mateix, per això emprem en un 90% exclusives amalgames i tintures cosmètiques d\'origen biològic certificado.',
    aboutText2: 'L\'atenció minuciosa i l\'ambient d\'absolut descans són l\'ànima del nostre saló executiu. El nostre objectiu és crear una experiència plaent des del primer instant, un espai obert on ensenyar directament les darreres tendències globals, assegurant la màxima qualitat de producte del mercat.',
    reviewsTitle: 'Opinions de clients reals',
    reviewsSub: 'Opinions recollides des de Google i Instagram directament.',
    contactTitle: 'On i quan trobar-nos',
    contactSub: 'Estem situades a l\'eix comercial principal, amb fàcil aparcament i accessibilitat garantida.',
    addressLabel: 'Adreça del saló',
    phoneLabel: 'Telèfons d\'atenció',
    emailLabel: 'Correu oficial',
    hoursTitle: 'Horari d\'Obertura Professional',
    openBadge: 'OBERT ARA',
    closedBadge: 'TANCAT ARA',
    mon: 'Dilluns',
    tue: 'Dimarts',
    wed: 'Dimecres',
    thu: 'Dijous',
    fri: 'Divendres',
    sat: 'Dissabte',
    sun: 'Diumenge',
    closed: 'Tancat',
    mapIframeTitle: 'Mapa de localització de la Perruqueria Elisenda',
    footerRights: 'Tots els drets reservats. Disseny premium executiu pro.',
    footerGithubNote: 'Aquesta pàgina és totalment estàtica i apte per a allotjament instantani a GitHub Pages.',
  },
  es: {
    metaTitle: 'Peluquería Elisenda',
    metaSub: 'Estilismo, Cabello & Tratamientos Estéticos de Salón',
    navHome: 'Inicio',
    navServices: 'Servicios',
    navGallery: 'Saber más / Galería',
    navBooking: 'Cita Online',
    navAbout: 'Historia & Reseñas',
    navContact: 'Contacto y Horario',
    heroTag: 'Elegancia, bienestar y tratamiento de confianza',
    heroTitle: 'Revela tu belleza natural con criterio profesional',
    heroSub: 'Salón ejecutivo pro especialista en estilismo capilar orgánico, balayage, peinados de eventos y cuidados estéticos cutáneos de gran nivel en L\'Espluga de Francolí.',
    heroCTA1: 'Pedir Cita Online',
    heroCTA2: 'Ver los Servicios',
    servicesTitle: 'Servicios Distinguidos',
    servicesSub: 'Explora nuestra carta profesional. Cada ritual está adaptado con cuidado a tus facetas físicas y personales.',
    catHair: 'Peluquería y Salud Capilar',
    catBeauty: 'Estética, Manos y Facial',
    mins: 'min',
    bookNow: 'Reservar',
    popularBadge: 'Más Solicitado',
    galleryTitle: 'Arte en movimiento',
    gallerySub: 'Instantáneas reales de nuestro trabajo diario: acabados de color, manicuras, recogidos y líneas de corte profesional.',
    bookingTitle: 'Tu momento de bienestar',
    bookingSub: 'Inicia el proceso seguro. Elige el servicio, la asesora de confianza y el período de tiempo para una atención exquisita sin demoras.',
    selectService: 'Selecciona un Servicio',
    selectStylist: 'Escoge la Estilista',
    anyStylist: 'Cualquier profesional (Elegir Marta o Elisenda)',
    selectDateTime: 'Día y Hora idóneos',
    personalData: 'Datos de Contacto',
    placeholderName: 'Tu nombre y apellido',
    placeholderPhone: 'Teléfono (ejemplo: 600 000 000)',
    placeholderNotes: '¿Algún comentario? (Alergias, cabello largo, corto...)',
    buttonConfirmBooking: 'Confirmar Reserva y Emitir Recibo',
    anyStylistLabel: 'Indiferente',
    bookingSuccess: '¡Tu cita se ha registrado con éxito!',
    bookingSuccessSub: '¡Nos vemos muy pronto! A continuación se muestra tu recibo listo para mostrar en tu móvil. Hemos almacenado tus citas localmente.',
    receiptTitle: 'Resumen del Recibo',
    receiptCode: 'Código de Seguridad',
    receiptStylist: 'Personal técnico',
    receiptDateTime: 'Fecha y hora',
    receiptPrice: 'Total estimado a pagar',
    bookingHistoryTitle: 'Tus últimas citas reservadas',
    aboutTitle: 'Más de 15 años de artesanía del cabello',
    aboutSub: 'El salón de alta costura capilar en L\'Espluga de Francolí',
    aboutText1: 'Fundado por Elisenda Tubau, Perruqueria Elisenda nació con el propósito de llevar el equilibrio estético de las grandes metrópolis a nuestra comarca de la Conca de Barberà. Consideramos que mimar el cabello es cuidar la salud integral, por ello empleamos más de un 90% de productos biológicos exclusivos.',
    aboutText2: 'El detalle minucioso y la atmósfera de absoluto reposo son el alma de nuestro salón ejecutivo. Deseamos entregarte una experiencia encantadora desde el primer minuto, ofreciendo las últimas tendencias globales garantizándote la máxima calidad del mercado actual.',
    reviewsTitle: 'Opiniones de clientes reales',
    reviewsSub: 'Comentarios recopilados directamente de Google e Instagram.',
    contactTitle: 'Dónde y cuándo encontrarnos',
    contactSub: 'Ubicados en el eje comercial central, disponiendo de fácil aparcamiento y comodidad de acceso.',
    addressLabel: 'Dirección del salón',
    phoneLabel: 'Teléfonos de atención',
    emailLabel: 'Correo oficial',
    hoursTitle: 'Horario de Apertura Profesional',
    openBadge: 'ABIERTO AHORA',
    closedBadge: 'CERRADO AHORA',
    mon: 'Lunes',
    tue: 'Martes',
    wed: 'Miércoles',
    thu: 'Jueves',
    fri: 'Viernes',
    sat: 'Sábado',
    sun: 'Domingo',
    closed: 'Cerrado',
    mapIframeTitle: 'Mapa de localización de la Peluquería Elisenda',
    footerRights: 'Todos los derechos reservados. Diseño premium ejecutivo pro.',
    footerGithubNote: 'Esta página es estática y optimizada para alojamiento instantáneo en GitHub Pages.',
  },
};
